os: linux
arch:
  - amd64
  - ppc64le
dist: boinic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - libhdf5-dev
      - gfortran
      - libatlas-base-dev
#For OpenCL:
      - ocl-icd-libopencl1
      - opencl-headers
      - libnuma1
      - ocl-icd-dev
      - ocl-icd-opencl-dev
# command to install dependencies

before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/before_install-linux.sh; fi"
#  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"

install:
  - "python ci/info_platform.py"
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --upgrade numpy"
  - "pip install --upgrade cython mako pybind11"
  - "pip install --upgrade h5py "
 # - if [ "${TRAVIS_CPU_ARCH}" == "ppc64le" ]; then
 #       sudo apt-get install qt5-default;
 #   fi
  - "pip install PyQt5"
  - "pip install --upgrade -r ci/requirements_travis.txt"
  - "python ci/info_platform.py"
  - "python setup.py build"
  - "python setup.py bdist_wheel"
  - "pip install --pre --no-index --find-links dist/ pyFAI"
 
# command to run tests
script:
  - "python run_tests.py -m"
  - "python ./run_tests.py -m --installed"
